import { invoke } from "@tauri-apps/api/core";
import { getCurrentWindow } from "@tauri-apps/api/window";
import { useCallback, useEffect, useRef, useState } from "react";
import { Icon } from "./icons";
import { CloudPage, DiagnosticsPage, HomePage, NodesPage, SettingsPage, SlotsPage, SubscriptionsPage } from "./pages";
import type { Action, AppSettings, AppSnapshot, Dashboard, MutationResult, NodeView, Page, ReloadScope } from "./types";
import { defaultSettings, emptyDashboard } from "./types";
import { Badge, Button } from "./ui";

const pages:{id:Page;label:string;icon:string}[]=[
  {id:"home",label:"概览",icon:"home"},{id:"subscriptions",label:"订阅",icon:"subscriptions"},
  {id:"nodes",label:"节点",icon:"nodes"},{id:"slots",label:"代理槽位",icon:"slots"},
  {id:"cloud",label:"云同步",icon:"cloud"},{id:"settings",label:"设置",icon:"settings"},
  {id:"diagnostics",label:"诊断",icon:"diagnostics"},
];
function TitleBar(){
  const appWindow=getCurrentWindow();const [maximized,setMaximized]=useState(false);
  useEffect(()=>{void appWindow.isMaximized().then(setMaximized);let dispose:(()=>void)|undefined;void appWindow.onResized(()=>appWindow.isMaximized().then(setMaximized)).then(fn=>dispose=fn);return()=>dispose?.()},[appWindow]);
  return <header className="titlebar" data-tauri-drag-region onDoubleClick={()=>void appWindow.toggleMaximize()}><div className="titlebar-brand" data-tauri-drag-region><span><img src="/node2socks-logo.png" alt=""/></span><strong>Node2Socks</strong></div><div className="window-controls" onDoubleClick={event=>event.stopPropagation()}><button aria-label="最小化" title="最小化" onClick={()=>void appWindow.minimize()}><Icon name="minimize"/></button><button aria-label={maximized?"还原":"最大化"} title={maximized?"还原":"最大化"} onClick={()=>void appWindow.toggleMaximize()}><Icon name={maximized?"restore":"maximize"}/></button><button className="close" aria-label="关闭到托盘" title="关闭到托盘" onClick={()=>void appWindow.close()}><Icon name="close"/></button></div></header>;
}
const mutationWarning=(value:unknown)=>value&&typeof value==="object"&&"warning" in value?String((value as MutationResult<unknown>).warning??""):"";
export function ToastNotice({kind,text,onClose}:{kind:"ok"|"error"|"warning";text:string;onClose:()=>void}){
  const remaining=useRef(kind==="error"?7000:kind==="warning"?5500:3500);const started=useRef(0);const timer=useRef<number|undefined>(undefined);
  const pause=()=>{if(timer.current!==undefined){window.clearTimeout(timer.current);timer.current=undefined;remaining.current=Math.max(0,remaining.current-(performance.now()-started.current))}};
  const resume=()=>{if(timer.current!==undefined)return;started.current=performance.now();timer.current=window.setTimeout(onClose,remaining.current)};
  useEffect(()=>{resume();return pause},[]);
  return <div className={"toast "+kind} role={kind==="error"?"alert":"status"} aria-live={kind==="error"?"assertive":"polite"} tabIndex={0} onPointerEnter={pause} onPointerLeave={resume} onFocus={pause} onBlur={event=>{if(!event.currentTarget.contains(event.relatedTarget as Node|null))resume()}}>{text}<button type="button" aria-label="关闭通知" onClick={onClose}>×</button></div>;
}
export default function AppShell(){
  const [page,setPage]=useState<Page>("home");const [data,setData]=useState<Dashboard>(emptyDashboard);const [nodes,setNodes]=useState<NodeView[]>([]);const [settings,setSettings]=useState<AppSettings>(defaultSettings);const [connected,setConnected]=useState(false);const [busy,setBusy]=useState("");const [notice,setNotice]=useState<{kind:"ok"|"error"|"warning";text:string}|null>(null);const pending=useRef(new Set<string>());
  const applySnapshot=useCallback((snapshot:AppSnapshot)=>{const errors:string[]=[];if(snapshot.dashboard.data){setData(snapshot.dashboard.data);setConnected(true)}else if(snapshot.dashboard.error){setConnected(false);errors.push(snapshot.dashboard.error)}if(snapshot.nodes.data)setNodes(snapshot.nodes.data);else if(snapshot.nodes.error)errors.push(snapshot.nodes.error);if(snapshot.settings.data)setSettings(snapshot.settings.data);else if(snapshot.settings.error)errors.push(snapshot.settings.error);if(errors.length)setNotice({kind:"error",text:errors.join("；")})},[]);
  const refresh=useCallback(async(scope:ReloadScope="all")=>{if(scope==="none")return;if(scope==="all"){applySnapshot(await invoke<AppSnapshot>("app_snapshot"));return}if(scope==="dashboard")setData(await invoke<Dashboard>("dashboard_snapshot"));if(scope==="nodes")setNodes(await invoke<NodeView[]>("list_node_views"));if(scope==="settings")setSettings(await invoke<AppSettings>("get_settings"))},[applySnapshot]);
  useEffect(()=>{void refresh("all").catch(error=>{setConnected(false);setNotice({kind:"error",text:String(error)})})},[refresh]);useEffect(()=>{document.documentElement.dataset.theme=settings.theme;document.documentElement.dataset.density=settings.density},[settings.theme,settings.density]);
  const action:Action=useCallback(async(label,run,options={})=>{if(pending.current.has(label))return {ok:false,error:"操作正在进行"};pending.current.add(label);setBusy(label);setNotice(null);try{const value=await run();await refresh(options.reload??"all");const warning=mutationWarning(value);if(warning)setNotice({kind:"warning",text:warning});else if(options.successNotice!==false)setNotice({kind:"ok",text:label+"成功"});return {ok:true,value,warning:warning||undefined}}catch(error){const message=String(error);setNotice({kind:"error",text:message});return {ok:false,error:message}}finally{pending.current.delete(label);setBusy("")}},[refresh]);
  const collapse=async()=>{const next={...settings,sidebarCollapsed:!settings.sidebarCollapsed};setSettings(next);const result=await action("保存侧栏状态",()=>invoke<MutationResult<AppSettings>>("update_settings",{settings:next}),{reload:"none",successNotice:false});if(!result.ok)setSettings(settings)};
  const body=page==="home"?<HomePage data={data} nodes={nodes} go={setPage} action={action}/>:page==="subscriptions"?<SubscriptionsPage data={data} action={action}/>:page==="nodes"?<NodesPage data={data} nodes={nodes} settings={settings} onSettings={setSettings} action={action}/>:page==="slots"?<SlotsPage data={data} nodes={nodes} action={action}/>:page==="cloud"?<CloudPage action={action}/>:page==="settings"?<SettingsPage settings={settings} onSettings={setSettings} data={data} action={action}/>:<DiagnosticsPage data={data} action={action}/>;
  return <main className={"app-shell "+(settings.sidebarCollapsed?"sidebar-collapsed":"")}><TitleBar/><aside className="sidebar"><div className="sidebar-head"><span>主菜单</span><button className="collapse-button" onClick={()=>void collapse()} title={settings.sidebarCollapsed?"展开侧栏":"折叠侧栏"}><Icon name="menu"/></button></div><nav>{pages.map(item=><button key={item.id} className={page===item.id?"selected":""} title={item.label} onClick={()=>setPage(item.id)}><Icon name={item.icon}/><span>{item.label}</span></button>)}</nav><div className="sidebar-status"><i className={data.coreRunning?"on":""}/><span><strong>{data.coreRunning?"代理核心运行中":"代理核心已停止"}</strong><small>本地模式 · 无需账号</small></span></div></aside><section className="workspace"><div className="command-strip"><span><Badge tone={connected?"success":"danger"}>{connected?"后端已连接":"后端不可用"}</Badge>{busy&&<small>{busy}…</small>}</span><Button icon={data.coreRunning?"stop":"play"} kind={data.coreRunning?"secondary":"primary"} disabled={!!busy} onClick={()=>void action(data.coreRunning?"停止核心":"启动核心",()=>invoke(data.coreRunning?"stop_core":"start_core"),{reload:"dashboard"})}>{data.coreRunning?"停止 Core":"启动 Core"}</Button></div>{notice&&<ToastNotice key={notice.kind+notice.text} kind={notice.kind} text={notice.text} onClose={()=>setNotice(null)}/>}<div className={"content-scroll "+(page==="nodes"?"node-canvas":"")} tabIndex={0} aria-label="页面内容"><div className="content">{body}</div></div></section></main>;
}