[package]
name = "node2socks-slot-manager"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
node2socks-domain = { version = "0.1.0", path = "../domain" }
rusqlite.workspace = true
serde.workspace = true
uuid.workspace = true

[dev-dependencies]
node2socks-storage = { path = "../storage" }
tempfile.workspace = true
